Fix gradle example
Gradle jib plugin (`com.google.cloud.tools.jib`) needs to be updated to 3.3.2 to eliminate the following error:

```text
com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Unknown mediaType: application/vnd.oci.image.index.v1+json
```

This is currently updated in the `update-build.gradle` branch of the `example-gradle` repository: https://github.com/buildsec/example-gradle/tree/update-build.gradle

Signed-off-by: Brad Beck <bradley.beck@gmail.com>